new_name_success_message = 'New Name created successfully'
new_name_error_message = 'New Name creation failed'
name_delete_success_message = 'Name deleted successfully'
name_delete_error_message = 'Name deletion failed'
name_does_not_exists = 'Name does not exists'
empty = ''
